---
- hosts: tag_tier_app
  remote_user: ubuntu
  become: true
  vars:
    hub_account: "{{ lookup('env','HUB_ACOUNT') }}"
  tasks:
    - name: Install Docker
      import_role:
        name: angstwad.docker_ubuntu

    - name: Pull hello-world image
      shell: docker pull {{hub_account}}/hello-world

    - name: Stop container
      shell: docker stop hello-world || true

    - name: Remove container
      shell: docker rm hello-world || true

    - name: Run hello-world container
      shell: docker run -d --name hello-world -p 8484:8484 {{hub_account}}/hello-world


- hosts: tag_tier_web
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install Nginx
      import_role:
        name: geerlingguy.nginx
      vars:
        # This is supposed to remove default nginx config
        # but the default path is wrong in the included role
        nginx_remove_default_vhost: true
        # can't overrive variable?
        nginx_default_vhost_path: /etc/nginx/conf.d/default.conf
        nginx_vhosts:
          - listen: "80"
            server_name: "hello"
            extra_parameters: |
              location / {
                proxy_pass http://app;
              }
        nginx_upstreams:
          - name: app
            servers: "{{ '{\"' + groups['tag_tier_app']| map('extract', hostvars, ['ec2_private_ip_address'])|list|join(':8484\",\"') + ':8484\"}' }}"
    # Remove default nginx config by hand
    # This is clearly not ideal as it fails the first time
    - name: Remove default config
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

- hosts: 127.0.0.1
  connection: local
  vars:
    dns_name: "{{ groups['tag_tier_web'] | map('extract', hostvars, ['ec2_public_dns_name'])|first}}"
  tasks:
    - debug: var=dns_name
    - action: uri url=http://{{dns_name}} return_content=yes
      register: webpage
    - action: uri url=http://{{dns_name}} return_content=yes
      register: webpage2
    - fail: msg='Doesnt look like round robin'
      when: webpage.content == webpage2.content
